--!strict

return table.freeze({
	Attack = table.freeze({
		Damage = 12,
		Height = 5,
		Cooldown = 0.65,
		Windup = 0.08,
		Active = 0.54,
		Knockback = 8,
		Stagger = 0.2,
	}),
	RisingCrash = table.freeze({
		Damage = 18,
		Range = 5,
		Height = 5,
		HalfAngle = 35,
		Cooldown = 7,
		Windup = 0.22,
		Duration = 0.45,
		Stamina = 20,
		ExposedDuration = 3,
		ExposedBonus = 0.1,
	}),
	GroundShock = table.freeze({
		Damage = 8,
		Range = 7,
		Height = 5,
		HalfAngle = 50,
		Cooldown = 10,
		Windup = 0.25,
		Duration = 0.5,
		Stamina = 20,
		PushDistance = 3,
		PushDuration = 0.16,
		SlowDuration = 1,
		SlowRatio = 0.75,
	}),
	Spin = table.freeze({
		Damage = 8,
		Radius = 6,
		Height = 5,
		Duration = 0.7,
		FirstHit = 0.2,
		Interval = 0.3,
		Hits = 2,
		Cooldown = 8,
		Stamina = 25,
		WalkSpeed = 10,
		TurnSpeed = math.pi * 4,
	}),
	Charge = table.freeze({
		Damage = 5,
		Range = 30,
		ContactRange = 3.5,
		Duration = 0.25,
		SlowDuration = 0.4,
		SlowRatio = 0.6,
		Cooldown = 6,
		Stamina = 20,
	}),
	Stagger = table.freeze({
		WeakWalkSpeed = 6,
		StrongKnockback = 10,
		GritMax = 100,
		GritWeight = 0.1,
		StrongDowngradeRatio = 0.65,
	}),
	Stamina = table.freeze({
		Max = 100,
		RegenPerSecond = 20,
		RegenDelay = 0.8,
		SprintPerSecond = 8,
		BlockPerSecond = 4,
		BlockHit = 12,
		Dash = 15,
		GuardBreakStagger = 0.6,
	}),
	BlockWalkSpeed = 8,
	PerfectGuard = table.freeze({
		Window = 0.18,
		Rearm = 0.6,
		StaminaRatio = 0.25,
		Recovery = 0.2,
	}),
	TrainingNPC = table.freeze({
		AttackRange = 3.2,
		Damage = 6,
		Knockback = 8,
		Cooldown = 0.65,
		Respawn = 3,
	}),
	WalkSpeed = 16,
	SprintSpeed = 24,
	DashSpeed = 75,
	DashDuration = 0.16,
	DashCooldown = 0.5,
})
